# Generated by Django 4.0.5 on 2022-06-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='number',
            field=models.IntegerField(verbose_name='Номер счета'),
        ),
    ]
